### ISSUE TITLE
Whisper in macro broken with 0.0.5

### ISSUE THREAD

**Issue by JordanRR** [spaceman02-ops/Inline-Table-Rolls#10]
Here is a chat macro I wrote for my game. With 0.0.5, it still works, but the whisper to gm is ignored, so my players see it all. I since reverted to 0.0.4 and it works again!

![image](https://user-images.githubusercontent.com/18445516/164307990-b7570b8c-6cb5-4a3c-a574-b53e2d17bf80.png)

**Comment by spaceman02-ops** [comment]
Fixed in latest release, sorry for the inconvenience

**Comment by JordanRR** [comment]
Thank you!
