### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Ulvtand** [spaceman02-ops/Inline-Table-Rolls#2]
Preferably a more detailed description, with examples. Not everyone has the knowledge and experience you have. ;)

**Comment by Ulvtand** [comment]
For example:

> #definition
> 
> @Compendium[better-rolltables.brt-story.B6oXhKONjSMBPmKB]{Human Male Names} AS {name}
> 
> [[14+4d6]] AS {age}
> 
> @Compendium[better-rolltables.brt-story.DWWhFdnbLyuydgNp]{NPC Physical Traits} AS {trait}
> 
> @Compendium[better-rolltables.brt-story.zIOBrxDOh7fCz2u2]{NPC Jobs} AS {job}
> 
> @Compendium[better-rolltables.brt-story.kVPnAOJHIRbfcvP6]{NPC Catchphrases} AS {catchphrase}
> 
> #story
> 
> {name} is a Human Male. {name} is {age} years old and {trait}
> 
> He is a {job}
> 
> #storyGM
> 
> {name} catchphrase is: {catchphrase}

**Comment by spaceman02-ops** [comment]
Added a youtube tutorial :D

**Comment by Ulvtand** [comment]
Nicely done and informative
