### ISSUE TITLE
Draw without replacement

### ISSUE THREAD

**Issue by IrishWolf** [spaceman02-ops/Inline-Table-Rolls#7]
It would be great if the inline table rolls would recognice the option for not replacing the rolled items.

**Comment by spaceman02-ops** [comment]
Hmm, could you elaborate on what you mean?

**Comment by IrishWolf** [comment]
When you create a roll table you have a checkbox for "Draw with Replacement?"
Checked means you can draw vom the table everyging as often as you like. Not checked every draw will lock the result so it only can be drawn once (till the gm unlock everything again).

![Draw replacement](https://user-images.githubusercontent.com/36819852/163711228-ce7c475b-9177-4b52-8207-03c3f58a5d3d.png)

In my cases for on-shots I like to have rolltables for looting of specific rooms but everything in there can only be found once (so drawing without replacement).

The inline table [[#table]] roll everytime with replacement even if the box is unchecked.

**Comment by spaceman02-ops** [comment]
Ah I understand now, I can check into this. Shouldn't be too hard to implement.

**Comment by spaceman02-ops** [comment]
Added this functionality in the latest release. Unfortunately it does not work with tables contained within compendiums at this time.
