### ISSUE TITLE
Draw from compendium?

### ISSUE THREAD

**Issue by crazycalya** [spaceman02-ops/Inline-Table-Rolls#8]
Is there a way to draw from compendiums, or just imported/local tables? Using compendiums improves performance so keeping too many local tables (especially ones with many results) is undesirable.

**Comment by spaceman02-ops** [comment]
I'll check into this and try to implement. I think it should be easy enough

**Comment by crazycalya** [comment]
That's awesome! Your module is great for my campaign but since I've moved everything to compendiums I've been struggling without it, I look forward to seeing what you come up with!

**Comment by spaceman02-ops** [comment]
Fixed in latest release
