### ISSUE TITLE
inconsistent dice-results

### ISSUE THREAD

**Issue by IrishWolf** [spaceman02-ops/Inline-Table-Rolls#9]
Hello,

I love the Inline-Table-Rolls, cause it is way more fancy to display the results then with a regular table-roll.

But in our last session we got the problem that the results were mixxed up. If the table has some rolling inside they will get these different for every player.

For example:
A table with rolling inside the results:
![image](https://user-images.githubusercontent.com/36819852/163728692-52160d82-fb6e-4b65-9f7a-46b22be11977.png)

called with th following macro:
![image](https://user-images.githubusercontent.com/36819852/163728713-c7644491-64a8-416f-930c-de7897da131f.png)

will get for 3 different players three different results:
(first result is with the macro the second result is with the roll-button directly on the table)
![image](https://user-images.githubusercontent.com/36819852/163728739-e8025b92-3c76-473a-9fb9-dfc0a7e2cfca.png)

That get us confused for a while^^'
It would be great if that can be fixxed in the future.

**Comment by spaceman02-ops** [comment]
Fixed in latest release
